/* ========================================================================
 * main_snippets.c  —  NOT A COMPILED FILE
 *
 * Drop these snippets into the matching USER CODE blocks of
 *   Core/Src/main.c         (auto-generated by CubeMX)
 *   Core/Src/stm32l4xx_it.c (auto-generated by CubeMX)
 * so that the BLE app lives alongside your CubeMX-generated peripheral init
 * without getting wiped out the next time you re-generate code.
 * ========================================================================*/

/* ------------------------------------------------------------------------
 * Core/Src/main.c
 * ------------------------------------------------------------------------ */

/* USER CODE BEGIN Includes */
#include "ble_app.h"
/* USER CODE END Includes */


/* USER CODE BEGIN 2                     <-- after all MX_* init functions  */
  if (BLE_App_Init() != 0) {
    Error_Handler();
  }
/* USER CODE END 2 */


/* USER CODE BEGIN WHILE */
  while (1)
  {
    BLE_App_Run();
/* USER CODE END WHILE */

/* ------------------------------------------------------------------------
 * Core/Src/stm32l4xx_it.c
 *
 * CubeMX will already generate the EXTI9_5_IRQHandler that calls
 * HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_5). We just need to override the
 * HAL_GPIO_EXTI_Callback so that the BlueNRG IRQ (PC5) wakes the BLE app.
 * ------------------------------------------------------------------------ */

/* USER CODE BEGIN EV                               (top-level USER CODE)   */
#include "ble_app.h"

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
  BLE_App_EXTI_Callback(GPIO_Pin);
}
/* USER CODE END EV */
